/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package creencias;

import java.util.Random;
import javax.swing.DefaultListModel;

/**
 *
 * @author jorgeeduardo
 */
public class ventana extends javax.swing.JFrame {
   DefaultListModel renglon;
    Random desor = new Random();
   jorge vector = new jorge(); 
    
    public ventana() {
        initComponents();
         renglon = new DefaultListModel();
         jList1.setModel(renglon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setBackground(new java.awt.Color(0, 255, 255));
        jList1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 1, 5, new java.awt.Color(102, 0, 102)));
        jScrollPane1.setViewportView(jList1);

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setText("ORDENAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 255));
        jButton2.setText("DESORDENAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 255, 51));
        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("28 CREENCIAS DE LOS ADVENTISTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        renglon.clear();
        renglon.addElement(vector.horta(0));
        renglon.addElement(vector.horta(1));
        renglon.addElement(vector.horta(2));
        renglon.addElement(vector.horta(3));
        renglon.addElement(vector.horta(4));
        renglon.addElement(vector.horta(5));
        renglon.addElement(vector.horta(6));
        renglon.addElement(vector.horta(7));
        renglon.addElement(vector.horta(8));
        renglon.addElement(vector.horta(9));
        renglon.addElement(vector.horta(10));
        renglon.addElement(vector.horta(11));
        renglon.addElement(vector.horta(12));
        renglon.addElement(vector.horta(13));
        renglon.addElement(vector.horta(14));
        renglon.addElement(vector.horta(15));
        renglon.addElement(vector.horta(16));
        renglon.addElement(vector.horta(17));
        renglon.addElement(vector.horta(18));
        renglon.addElement(vector.horta(19));
        renglon.addElement(vector.horta(20));
        renglon.addElement(vector.horta(21));
        renglon.addElement(vector.horta(22));
        renglon.addElement(vector.horta(23));
        renglon.addElement(vector.horta(24));
        renglon.addElement(vector.horta(25));
        renglon.addElement(vector.horta(26));
        renglon.addElement(vector.horta(27));
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        renglon.clear();
        renglon.addElement(vector.desordenar(0));
        renglon.addElement(vector.desordenar(1));
        renglon.addElement(vector.desordenar(2));
        renglon.addElement(vector.desordenar(3));
        renglon.addElement(vector.desordenar(4));
        renglon.addElement(vector.desordenar(5));
        renglon.addElement(vector.desordenar(6));
        renglon.addElement(vector.desordenar(7));
        renglon.addElement(vector.desordenar(8));
        renglon.addElement(vector.desordenar(9));
        renglon.addElement(vector.desordenar(10));
        renglon.addElement(vector.desordenar(11));
        renglon.addElement(vector.desordenar(12));
        renglon.addElement(vector.desordenar(13));
        renglon.addElement(vector.desordenar(14));
        renglon.addElement(vector.desordenar(15));
        renglon.addElement(vector.desordenar(16));
        renglon.addElement(vector.desordenar(17));
        renglon.addElement(vector.desordenar(18));
        renglon.addElement(vector.desordenar(19));
        renglon.addElement(vector.desordenar(20));
        renglon.addElement(vector.desordenar(21));
        renglon.addElement(vector.desordenar(22));
        renglon.addElement(vector.desordenar(23));
        renglon.addElement(vector.desordenar(24));
        renglon.addElement(vector.desordenar(25));
        renglon.addElement(vector.desordenar(26));
        renglon.addElement(vector.desordenar(27));
        
                   
           
            
                       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        renglon.clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
